### ISSUE TITLE
The DLL cant save ProtectedStrings with the IsCompiled property set to true

### ISSUE THREAD

**Issue by metatablecat** [MaximumADHD/Roblox-File-Format#8]
This code should *theoretically* add a ModuleScript with a compiled protected string. However, post-analysis shows that the property is being saved as a regular string

```vb
Sub Main(args As String())
	Dim Rbxm As RobloxFile = RobloxFile.Open("D:/test.rbxm")
	Dim Bytecode As Byte() = FileIO.FileSystem.ReadAllBytes("D:/bytecode.luauc")
	Dim Folder = Rbxm.FindFirstChild("Folder")

        Dim SharedPluginConstants As New ModuleScript

        Dim Protect As ProtectedString = Bytecode
        SharedPluginConstants.Source = Protect
        SharedPluginConstants.Name = "SharedPluginConstants"
        SharedPluginConstants.Parent = Folder

        Console.WriteLine(SharedPluginConstants.Source.IsCompiled) '--> true
        Rbxm.Save("D:/test-with-bc.rbxm")
End Sub
```
(yes ik it's vb im too lazy to write this test in C#)

**Comment by MaximumADHD** [comment]
WELL… the nuance here is that Roblox doesn’t actually support PropertyType 29 for regular files. Reportedly it requires a special flag to be set on the C++ end and will just be treated as invalid otherwise. This may have changed since and I will double check if it’s still the case, but this should be as simple as just mapping typeof(ProtectedString) to PropertyType.ProtectedString in the static `Property.Types` table.

**Comment by metatablecat** [comment]
From what I've tested (by dragging a compiled BuiltInPlugin into the `/Plugins/` folder, it runs the code as expected. Yes I know there's a massive security risk here.
